### ISSUE TITLE
how to train  feature with ResNET_TF2 (CALF model)

### ISSUE THREAD

**Issue by 419291821** [SilvioGiancola/SoccerNetv2-DevKit#11]

**Comment by SilvioGiancola** [comment]
Hi @419291821 ,

Could you provide us with a description of your issue? If you need to train CALF with ResNET_TF2 instead of ResNET_TF2_PCA512, all you have to do is set the parameters `--features=ResNET_TF2.npy --num_features=2048` in the training function. In other words:

```bash 
python src/main.py --SoccerNet_path=/path/to/SoccerNet/ \
--features=ResNET_TF2.npy \
--num_features=2048 \
--model_name=CALF_v2 \
--batch_size 32 \
--evaluation_frequency 20 \
--chunks_per_epoch 18000 
```

Note that training with larger features makes the training unstable, and only provide a ~1% boost when it converges. You also might need to reduce the batch_size to fit in your GPU memory.

I hope that solve your issue, feel free to re-open it if it does not solve your issue.

Best,
