### ISSUE TITLE
Making player bounding box code 

### ISSUE THREAD

**Issue by mcjeong95** [SilvioGiancola/SoccerNetv2-DevKit#19]
Hi, I read your Camera Calibration and Player Localization paper, and it was awesome work.

So, I'd like to try to add "ball detection" process, since you detected players only.

Unfortunately, I couldn't find a code which makes **"player_boundingbox_maskrcnn.json" and "field_calibration_ccbv.json"** files as output.

Could you let me know where can I find the code?

Best Regards.

**Comment by SilvioGiancola** [comment]
Hi @mcjeong95 ,

Thank you for your kind words! You did right raising that issue, we will do our best to help you :)

We extracted the field calibration features with CCBV (hence the name "field_calibration_ccbv.json"), the which code is available here: https://github.com/evs-broadcast/CCBV 

Similarly, for the player bounding boxes ("player_boundingbox_maskrcnn.json"), we used the code from MaskRCNN-benchmark available here: https://github.com/facebookresearch/maskrcnn-benchmark , but note that you could use any other object detection codebase such as mmdetection (https://github.com/open-mmlab/mmdetection) for instance.

We inferred both field calibrations and player bounding boxes at 2fps, using the same code we used to extract the global frame features ResNET: https://github.com/SilvioGiancola/SoccerNetv2-DevKit/tree/main/Features . Those are in fact input features for action spotting :)

I hope that helps,

Cheers!

**Comment by mcjeong95** [comment]
Thanks for your kind reply!

And I have two additional questions.

1. Do you have any plans to add **"ball detection"** in your works? I think the coordinate of ball could be quite important information for action spotting.

2. Is there any reason that you used **average RGB color** of bounding boxes rather than **fixed colors**(e.g. 'red' for Home Team, and 'blue' for Away Team)? In my opinion, **average RGB color** represents only for one certain match, and **fixed colors** can represents general matches. 

If I miss some points, feel free to let me know :)

**Comment by cioppaanthony** [comment]
Hi @mcjeong95,

These are both very good questions.

1. Yes indeed, but instead of simply applying a network as we did for the players, we are currently manually annotating the ball in a subset of SoccerNet frames, on which models can then be trained. Stay tuned in the next few months for more details. In the meantime, if you need the ball for all frames at 2fps like the players, you can simply use one of the mmdetection models as Silvio suggested as some of them also provide ball detection alongside person detection.

2. We saved the average color simply as a bonus information, just to have some feature about the player to possibly discriminate them. We did not include a complete team discrimination algorithm to the processed information as this is still a hot topic of research. Anyway, this can be done by choosing a proper algorithm (e.g. https://ieeexplore.ieee.org/document/9025473) and leveraging the provided bounding boxes. This is also a feature that we are working on for the future version of SoccerNet.

I hope this answers your questions. :-)

**Comment by mcjeong95** [comment]
That sounds perfect, my curiosities are totally resolved.

Thanks for all your helps and I'll keep stay tuned in your next fabulous research :)

**Comment by cioppaanthony** [comment]
Many thanks for your interest! :-)
