### ISSUE TITLE
Question relating to CALF Average-mAP metric

### ISSUE THREAD

**Issue by Wilann** [SilvioGiancola/SoccerNetv2-DevKit#30]
Hi, 

I'm studying the metric used for CALF in Task1-ActionSpotting - specifically `average_mAP`, `delta_curve`, and `compute_mAP` in `metrics_visibility_fast.py`.

I understand that you use `delta=5` seconds around each GT label, and `num_intervals=12` intervals (also `num_classes=171). If this is the case, I assume we can...

In `average_mAP`, change,
```
integral_unshown = 0.0
for i in np.arange(len(mAP_unshown)-1):
    integral_unshown += 5*(mAP_unshown[i]+mAP_unshown[i+1])/2
a_mAP_unshown = integral_unshown/(5*(len(mAP_unshown)-1))
a_mAP_unshown = a_mAP_unshown*17/13
```
into 
```
integral_unshown = 0.0
for i in np.arange(len(mAP_unshown)-1):
    integral_unshown += delta * (mAP_unshown[i] + mAP_unshown[i+1]) / 2
a_mAP_unshown = integral_unshown / (delta * (len(mAP_unshown)-1))
a_mAP_unshown = a_mAP_unshown * num_classes / (num_intervals+1)
```

In `delta_curve`, change `(np.arange(12)*5 + 5)*framerate)` into `(np.arange(num_intervals)*delta + delta)*framerate`

In `compute-mAP`, change 
1. `for j in np.arange(11)/10:` into `for j in np.arange(num_intervals-1)/10:`, and
2. `mAP_per_class = AP/11` into `mAP_per_class = AP / num_intervals-1`

Are these 3 assumptions correct? 

Also, in `average_mAP`, when averaging the mAPs, how come `a_mAP` and `a_mAP_visible` are identical, but `a_mAP_unshown` has an extra line: `a_mAP_unshown = a_mAP_unshown*17/13`?

Hoping you can help me better understand the metric your team used. Thank you for reading!

**Comment by cioppaanthony** [comment]
Hi @Wilann,

Actually, there are a few mistakes in what you describe. First, I suggest you to check out the replay of our first live session on the challenge where we explained the Average-mAP in detail. I think this might help you understand better the concept behind it: https://www.youtube.com/watch?v=n-fWUr2SKqQ&t=1579s (26:19).

Actually, the average mAP uses several deltas, ranging from 5 seconds to 60 seconds in this fashion [5,10,15,...,50,55,60], so basically you have 12 intervals of 5 seconds each. In your first codes, it should be delta_step instead of delta (just to be consistent with the usual naming).

In compute mAP, the number 11 is not linked to the number of steps!! It is just a way to get a list containing the thresholds on the recall: [0,0.1,0.2,0.3,..,0.9,1], which is used in the computation of the AP as in Pascal VOC. 

Finally, in our dataset, there are 4 classes out of the 17 for which there are no instances of these classes that are unshown. Since our code computes the average-mAP per class on all classes, these 4 particular classes will have 0% performance (as there are no positive groundtruths). Since the a_mAP is linear with respect to the classes, we can remove these 4 classes from the computation using the formula:  `a_mAP_unshown = a_mAP_unshown*17/13`. This is exactly equivalent as calculating the average_mAP only on the 13 unshown classes.

I hope this helps, don't hesitate to get back to me if you have other questions.

**Comment by Wilann** [comment]
Hi @cioppaanthony,

Thank you so much for your reply.

In your example for the several deltas (5s to 60s), I understand that the first interval is 2.5s before and 2.5s after the GT label, the second interval is 5s before and 5s after, and so on?

Ah I understand that 11 isn't linked to any of these variables now. I'm definitely unfamiliar of Pascal VOC and custom metrics in general. 

I now understand where the 13 comes from, but am lost on why average-mAP is linear with respect to clsses (maybe the wording is confusing me - I'm not sure). Consequently, I'm also confused on how the formula `a_mAP_unshown = a_mAP_unshown*17/13` removes those 4 classes from the computation. 

As a side note, I actually made sure to watch the first 2 tutorials several times before opening these issues, but still didn't understand everything. Appologizes if these are more beginner questions! Thank you again for your time. Really appreciate it.

**Comment by cioppaanthony** [comment]
Hi @Wilann,

Don't worry about the questions, we're here to answer them. :-)

That's right, the interval is shared between after and before the ground-truth label.  

The Average-mAP is simply the mean of the Average-AP computed for each of the 17 classes. (Note: In the code, we first compute the mean over the classes for the AP, and then the area under the curve for the average-mAP with the trapezoidal interpolation. But since both operations are linear, we can simply inverse their order for the sake of clarity in the following). 

So imagine that you have 17 scores of average-AP in a list and you do `mean(mylist)` to get the average-mAP. This `mean` operation is linear with respect to its elements, as it is just the sum of the elements divided by the number of elements in the list. Now, you know that for 4 of these classes, their elements will be 0 not matter what you predict (since there are no positive GT). If you want to remove them from the list, you can either do `mean(mylist_removed_4_elements)` (and that's perfectly fine) or you can do `mean(mylist)*17/13`. This is equivalent to saying that in the mean, instead of dividing by 17, I'm now dividing by 13 as `(sum(mylist)/17)*17/13`. Both 17 cancels and you are now dividing by 13, the number of classes without the 4 that we don't want. In the sum, since these 4 classes have strictly 0 value, they do not affect the sum (adding 0 does not change the sum) and hence, it is equivalent to having the `sum(my_list_removed_4_elements)`. 

You can try it yourself with chosen values to really get it. Otherwise, if you prefer, simply remove the 4 performances and remove them from your list before applying the mean, since that's equivalent. 

Have I made it clearer for you? ;-)

**Comment by Wilann** [comment]
Hi @cioppaanthony, 

Ahhh I see now. So the purpose of the formula, is so that the unshown classes without GT labels don't negatively & incorrectly affect the overall metric. Basically, if we were to divide by 17, that would be wrong since we only have 13 elements to average over. 

For me, I'll probably stick to just using something like `mean(mylist_removed_4_elements)` as it's more intuitive for me. 

Thank you so much for the explanation - it was very clear and insightful! :)
