### ISSUE TITLE
Initialization of NetVLAD++

### ISSUE THREAD

**Issue by gmberton** [SilvioGiancola/SoccerNetv2-DevKit#46]
Hi, given that the original NetVLAD is initialized with clusters computed by running a kNN on the features (see [this link](https://github.com/Nanne/pytorch-NetVlad/blob/master/main.py#L231) as an example), I am curious: why don't you do this in NetVLAD++?
Also, I saw that you [imported the NearestNeighbor package in netvlad.py](https://github.com/SilvioGiancola/SoccerNetv2-DevKit/blob/main/Task1-ActionSpotting/TemporallyAwarePooling/src/netvlad.py#L5), so I think that perhaps you tried it but it didn't improved the results?

**Comment by SilvioGiancola** [comment]
Hi @gmberton , great catch! I actually followed the implementation of [LOUPE](https://github.com/antoine77340/LOUPE/blob/master/loupe.py) originally built in TensorFlow, and it did not consider such initialization. I don't recall using nor trying the NearestNeighbor package, even if it is still commented in netvlad.py. 

Actually, I don't believe NetVLAD is still learning clusters in the same way than VLAD does, so I am not sure the kNN initialization is important in here. I gave a [talk about NetVLAD](https://www.silviogiancola.com/talk/netvlad-theory-and-applications/) a year ago, and if you check on slide 9, `w_k, b_k and c_k are learned independently` (also, see [original paper](https://arxiv.org/pdf/1511.07247.pdf) after Equation 4). Because `w_k` and `b_k` are not functions of `c_k` anymore, I believe the concept of centroid in NetVLAD is a bit misleading, and does not hod anymore like it was the case in VLAD.

Now, feel free to try out running a kNN on the features and let me know if it improves the results! :)

**Comment by gmberton** [comment]
Thanks for your quick response! I am definitely sure that the kNN initialization is important for NetVLAD, at least in its original task of geolocalization/place recognition, as I have been working with it for a long time now. However, the use of NetVLAD in this scenario (video) is quite different from how it was used originally, so I agree those results might not hold here (e.g. the original version takes as input 3D features from the last layer of a VGG, and also the implementation looks slightly different).
If I manage to perform that experiment, I'll let you know how it goes :)
